name: CI

on:
  push:
    branches:
      - master

env:
  # Add your encrypted variables here as GitHub Secrets
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Decrypt Google Cloud Service Account Key
        run: |
          echo "$GCP_SERVICE_ACCOUNT_KEY" | base64 -d > ./service-account.json

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ./service-account.json
          project_id: multi-k8s-394514
          zone: asia-south1
          cluster: multi-k8s

      - name: Build Docker image
        run: docker build -t Aditya250401/react-test -f ./client/Dockerfile.dev ./client

      - name: Log in to Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Test using Docker
        run: docker run -e CI=true Aditya250401/react-test npm test
